/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.ChucVu;
import DomainModels.TacGia;
import java.io.File;
import java.io.FileOutputStream;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultButtonModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xwpf.usermodel.Borders;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.TableRowAlign;
import org.apache.poi.xwpf.usermodel.TableWidthType;
import org.apache.poi.xwpf.usermodel.UnderlinePatterns;
import org.apache.poi.xwpf.usermodel.VerticalAlign;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableCell;
import org.apache.poi.xwpf.usermodel.XWPFTableRow;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTTblWidth;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.STTblWidth;

/**
 *
 * @author TBC
 */
public class testGenerateWord extends javax.swing.JFrame {

    private DefaultTableModel dtm;

    private ArrayList<ChucVu> ds;

    public testGenerateWord() {
        initComponents();

        dtm = (DefaultTableModel) tblT.getModel();

        ds = new ArrayList<>();
        ChucVu d = new ChucVu();
        d.setId("3242");
        d.setMa("23");
        d.setTen("232");
        d.setVaiTro(1);

        ChucVu d2 = new ChucVu();
        d2.setId("555");
        d2.setMa("25553");
        d2.setTen("55");
        d2.setVaiTro(1);

        ChucVu d3 = new ChucVu();
        d3.setId("55");
        d3.setMa("55");
        d3.setTen("2352");
        d3.setVaiTro(11);
        ds.add(d);
        ds.add(d2);
        ds.add(d3);

        loadTb();
    }

    private void loadTb() {
        dtm.setRowCount(0);
        for (ChucVu d : ds) {
            dtm.addRow(new Object[]{
                d.getId(),
                d.getMa(),
                d.getTen(),
                d.getVaiTro()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        test = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblT = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        test.setText("xuất");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });

        tblT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"6", "5", "4", "y"},
                {"4", "5", "3", "y"},
                {"4", "5", null, "u"},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblT);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(test)
                .addGap(117, 117, 117)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(test)
                    .addComponent(jButton1))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed

        JFileChooser file = new JFileChooser("C:"); // mo hop thoai theo duong dan
        int x = file.showOpenDialog(this); // mo hop thoai dialog

        if (x != 0) {
            return; // k return se ban loi
        }

        File file1 = file.getSelectedFile(); // tao file bang fchoose da chon o tren

        if (file1.toString().lastIndexOf(".") == -1) {
            file1 = new File(file1.toString() + ".doc"); // thêm đuôi
        }

        try {
            XWPFDocument document = new XWPFDocument();
//            FileOutputStream out = new FileOutputStream(new File("c:\\Downloads\\chillyfacts.docx"));
            XWPFParagraph paragraph0 = document.createParagraph();
            XWPFRun run0 = paragraph0.createRun();
            run0.setFontSize(30);
            paragraph0.setAlignment(ParagraphAlignment.CENTER);
            run0.setText("Hóa Đơn Bán Hàng");
            run0.setBold(true);
//            run0.addBreak();

            XWPFParagraph paragraph2 = document.createParagraph();
            XWPFRun run = paragraph2.createRun();
            paragraph2.setSpacingAfter(60);

            run.setText("Khách hàng: ");
            run.setText("kh001");
            run.addBreak();

            XWPFParagraph paragraph3 = document.createParagraph();
            XWPFRun run3 = paragraph3.createRun();
            paragraph3.setSpacingAfter(60);
            run3.setText("Địa chỉ: ");
            run3.setText("Hà Nội");
            run3.setUnderline(UnderlinePatterns.WAVE);
            run3.addBreak();

            XWPFParagraph paragraph4 = document.createParagraph();
            XWPFRun run4 = paragraph4.createRun();
            paragraph4.setSpacingAfter(60);
            run4.setText("Sdt: ");
            run4.setText("2311312");
            run4.addBreak();

//            paragraph4.setBorderBottom(Borders.BIRDS_FLIGHT);
            //create table
            XWPFTable table = document.createTable();
            table.setCellMargins(200, 200, 200, 200);
            table.setTableAlignment(TableRowAlign.CENTER);

            // chieu rong cua bang
            CTTblWidth width = table.getCTTbl().addNewTblPr().addNewTblW();
            width.setType(STTblWidth.DXA);
            width.setW(BigInteger.valueOf(9000));

            //create first row
            XWPFTableRow row0 = table.getRow(0);
            row0.setHeight(500);
            XWPFTableCell cell0 = row0.getCell(0);
            cell0.setText("STT");
            cell0.setVerticalAlignment(XWPFTableCell.XWPFVertAlign.CENTER);

            XWPFTableCell cell1 = row0.createCell();
//            cell1.setWidth("1000");
            cell1.setWidthType(TableWidthType.AUTO);
            cell1.setText("ma san pham");
            cell1.setVerticalAlignment(XWPFTableCell.XWPFVertAlign.CENTER);

            XWPFTableCell cell2 = row0.createCell();
            cell1.setWidthType(TableWidthType.AUTO);
            cell2.setText("ten san pham");
            cell2.setVerticalAlignment(XWPFTableCell.XWPFVertAlign.CENTER);

            XWPFTableCell cell3 = row0.createCell();
            cell1.setWidthType(TableWidthType.AUTO);
            cell3.setText("số lượng");
            cell3.setVerticalAlignment(XWPFTableCell.XWPFVertAlign.CENTER);

            XWPFTableCell cell4 = row0.createCell();
            cell1.setWidthType(TableWidthType.AUTO);
            cell4.setText("gia san pham");
            cell4.setVerticalAlignment(XWPFTableCell.XWPFVertAlign.CENTER);

int i = 1;
            for (ChucVu d : ds) {
//                table.setCellMargins(100, 100, 100, 100);
                XWPFTableRow tableRowTwo = table.createRow();
                tableRowTwo.getCell(0).setText(i++ +"");
                tableRowTwo.getCell(1).setText(d.getMa());
                tableRowTwo.getCell(2).setText(d.getTen());
                tableRowTwo.getCell(3).setText(d.getTen());
                tableRowTwo.getCell(4).setText(d.getVaiTro() + "");

            }
            
             XWPFParagraph paragraph8 = document.createParagraph();
            XWPFRun run8 = paragraph0.createRun();
            run8.setFontSize(13);
            paragraph0.setAlignment(ParagraphAlignment.LEFT);
            run8.setText("Hóa Đơn Bán Hàng");
            run8.setBold(true);

//            XWPFRun paragraphOneRunThree = paragraph2.createRun();
//
//            // paragraphOneRunThree.setStrike(true);
//            paragraphOneRunThree.setFontSize(30);
//            paragraphOneRunThree.setSubscript(VerticalAlign.SUBSCRIPT);
//            paragraphOneRunThree.setText(" Font Styles");
            try {
                FileOutputStream fos = new FileOutputStream(file1.toString());
                document.write(fos);
                fos.close();
                JOptionPane.showMessageDialog(this, "xuất thành công");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "xuất thất bại, vui thử nơi lưu trữ khác");
                e.printStackTrace();
            }
//            document.write(out);
//            out.close();
            System.out.println("createparagraph.docx written successfully");
        } catch (Exception e) {
            // TODO: handle exception
            JOptionPane.showMessageDialog(this, "xuất thất bại");
        }
    }//GEN-LAST:event_testActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testGenerateWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testGenerateWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testGenerateWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testGenerateWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testGenerateWord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblT;
    private javax.swing.JButton test;
    // End of variables declaration//GEN-END:variables
}
